# Generated by Django 4.1 on 2022-08-27 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('aadhar', models.ImageField(blank=True, null=True, upload_to='verification/profile/')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='verification/profile/')),
                ('is_verify', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Not-Verified', 'Not-Verified')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('floor', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Un-Furnished', 'Un-Furnished')], max_length=50)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBookingModel',
            fields=[
                ('verified_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.verificationmodel')),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_request_created', to='base.room')),
            ],
        ),
    ]
